# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "*"       # run for all branches
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      # 👇 Deploys branch previews
      - name: Deploy Preview
        if: github.ref != 'refs/heads/main'
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --yes

      # 👇 Deploys production only when pushing to main
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
